# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT! python -m grpc_tools.protoc -I./grpc/ --python_out=./grpc/ --grpc_python_out=./grpc/ grpc.proto
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x08tasklist\"\x14\n\x06\x43hatId\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x04Task\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.tasklist.ChatId\x12\x0c\n\x04text\x18\x02 \x01(\t\"E\n\nTaskUpdate\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.tasklist.ChatId\x12\x0b\n\x03num\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\"6\n\tTaskIdent\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.tasklist.ChatId\x12\x0b\n\x03num\x18\x02 \x01(\x05\"!\n\x11OperationResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"?\n\x0cTaskResponse\x12\x0b\n\x03num\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x14\n\x0cis_completed\x18\x03 \x01(\x08\x32\xcd\x02\n\x0bTaskService\x12;\n\nCreateTask\x12\x0e.tasklist.Task\x1a\x1b.tasklist.OperationResponse\"\x00\x12\x38\n\x08GetTasks\x12\x10.tasklist.ChatId\x1a\x16.tasklist.TaskResponse\"\x00\x30\x01\x12\x41\n\nUpdateTask\x12\x14.tasklist.TaskUpdate\x1a\x1b.tasklist.OperationResponse\"\x00\x12\x42\n\x0c\x43ompleteTask\x12\x13.tasklist.TaskIdent\x1a\x1b.tasklist.OperationResponse\"\x00\x12@\n\nRemoveTask\x12\x13.tasklist.TaskIdent\x1a\x1b.tasklist.OperationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATID']._serialized_start=24
  _globals['_CHATID']._serialized_end=44
  _globals['_TASK']._serialized_start=46
  _globals['_TASK']._serialized_end=96
  _globals['_TASKUPDATE']._serialized_start=98
  _globals['_TASKUPDATE']._serialized_end=167
  _globals['_TASKIDENT']._serialized_start=169
  _globals['_TASKIDENT']._serialized_end=223
  _globals['_OPERATIONRESPONSE']._serialized_start=225
  _globals['_OPERATIONRESPONSE']._serialized_end=258
  _globals['_TASKRESPONSE']._serialized_start=260
  _globals['_TASKRESPONSE']._serialized_end=323
  _globals['_TASKSERVICE']._serialized_start=326
  _globals['_TASKSERVICE']._serialized_end=659
# @@protoc_insertion_point(module_scope)
